### ISSUE TITLE
pgp key used to sign releases

### ISSUE THREAD

**Issue by filippog** [rtyley/bfg-repo-cleaner#134]
hi,
I was trying to verify the 1.12.8 release of bfg linked from the website, is the public key published anywhere on the website too? Also `1E28BEA3` used for 1.12.8 has expired

```
$ gpg --verify bfg-1.12.8.jar.asc bfg-1.12.8.jar
gpg: Signature made Tue 15 Dec 2015 17:22:25 GMT using RSA key ID 1E28BEA3
gpg: Good signature from "Roberto Tyley <roberto.tyley@gmail.com>"
gpg: Note: This key has expired!
Primary key fingerprint: 0EC0 00F1 A22C 8F90 8A69  6924 5C3D 8C06 1E28 BEA3
$ gpg --list-key 1E28BEA3
pub   2048R/1E28BEA3 2011-11-29 [expired: 2015-11-28]
uid                  Roberto Tyley <roberto.tyley@gmail.com>

```

thanks!

**Comment by rtyley** [comment]
Thanks for the heads up about my expired key! I've generated a new one, and added a download to it on the BFG homepage:

![image](https://cloud.githubusercontent.com/assets/52038/14002592/e3673d50-f144-11e5-9a71-6a6d9cade36e.png)

All releases of the BFG from v1.12.12 onwards will be signed with this key - v1.12.12 is not yet visible on the site because search.maven.org has not indexed it yet, but it is already available for download:

http://repo1.maven.org/maven2/com/madgag/bfg/1.12.12/

**Comment by filippog** [comment]
:+1: thanks @rtyley that was quick!
