### ISSUE TITLE
how to remove path/to/file.secrity?

### ISSUE THREAD

**Issue by netroby** [rtyley/bfg-repo-cleaner#187]
I have a file in path/to/file.security. 
I run 
```
bfg --delete-files path/to/file.security my-repo.git
```
It show me error: 
```
Error: *** Can only match on filename, NOT path *** - remove '/' path segments
```

**Comment by codeHatcher** [comment]
I'm  having this same issue, how did you solve it?

**Comment by codeHatcher** [comment]
Actually, I ended up solving it by going to the directory that had the file I cared about and then running it as such `java -jar /usr/local/bin/bfg.jar --delete-files private.key ../../`

**Comment by yeago** [comment]
I think the commender above sought to get around the path requirement by cd'ing into the directory, however, it would have been equivalent to simply do `java -jar /usr/local/bin/bfg.jar --delete-files SOMEFILE.FOO` without cd'ing. The command will destroy any SOMEFILE.FOO in the entire repo....so its actually a potentially catastrophic advice to follow.

**Comment by zheng-raymond** [comment]
@codeHatcher  I am facing the same question, are you only trying to delete the SPECIFIC `private.key` file INSTEAD OF ALL instances of `private.key` ? Does that work?

**Comment by javabrett** [comment]
The only way to delete a file qualified by a path using current BFG is to lookup its object id and address/delete it that way.

**Comment by TV4Fun** [comment]
Why is this closed? This is a pretty major deficiency. What do I do if I have more than one directory named `results` and I only want to delete one of them? Scrubbing anything in your repo based on a blob match on the filename alone is potentially disastrous.

**Comment by milahu** [comment]
> git-filter-repo

```sh
git gc # workaround for "this does not look like a fresh clone"
git filter-repo --invert-paths --path path/to/file.security
```

**Comment by stephyswe** [comment]
Any windows users coming here and wondering how to install git-filter-repo .
if you have python3. you should not wait.

Do a `python3 -m pip install --user git-filter-repo` based on tip from https://superuser.com/a/1589985
after that you can use git-filter-repo with 

```
git gc
git filter-repo --invert-paths --path src/constant/index.ts --force
```

**Comment by ahstram** [comment]
The best solution I've found is to refer to the object by its object ID, rather than its file or directory name, which others have rightfully pointed out will be ambiguous in the case that multiple files share the same file or directory name.

I agree that it is very destructive behavior to take ambiguity to mean "delete everything that matches". Hence the need to refer to objects by their object ID, not file or directory name.

I've been using this one-liner to see a list of objects, sorted by descending file size:

```bash
git rev-list --objects --all \
    | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
    | sed -n 's/^blob //p' | sort -k2 -nr \
    | $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

If I then want to delete all files in the directory `path/to/directory`, I use AWK to strip down to only those lines where the 3rd column contains my directory string, while being sure to add a `^` at the beginning of my pattern to ensure that `another/path/to/directory` does NOT match, and escaping `/` with `\/`

```bash
git rev-list --objects --all \
    | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
    | sed -n 's/^blob //p' | sort -k2 -nr \
    | $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest \
    | gawk '($3~/^path\/to\/directory\//){print $0}'
```

Finally, once I've confirmed everything looks good, I write column 1 (blob IDs) to a file `list-of-blobs.txt`:

```bash
git rev-list --objects --all \
    | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
    | sed -n 's/^blob //p' | sort -k2 -nr \
    | $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest \
    | gawk '($3~/^path\/to\/directory\//){print $1}' > list-of-blobs.txt
```

and use bash to remove all objects listed in `list-of-blobs.txt`

```bash
java -jar ~/git/bfg-1.14.0.jar --strip-blobs-with-ids `list-of-blobs.txt`
```

Hope this helps!
