### ISSUE TITLE
Remove Political Agenda

### ISSUE THREAD

**Issue by JackMordaunt** [rtyley/bfg-repo-cleaner#205]
So can someone explain to me why a git tool shows me this after using it:

```
--  
You can rewrite history in Git - don't let Trump do it for real!  
Trump's administration has lied consistently, to make people give up on ever  
being told the truth. Don't give up: https://github.com/bkeepers/stop-trump  
--  
```

Surely I'm not the who gets pissed off by this. 
Not everyone is American. 
Not everyone cares about politics, or your political agenda.
It's actually kind of offensive pushing your shit like this in a free tool.

Anyway, unless or until this political propaganda is removed I won't be using or recommending `bfg-repo-cleaner` to anyone.

**Comment by smihulet** [comment]
Here here!!!

**Comment by rtyley** [comment]
> So can someone explain to me why a git tool shows me this after using it:

The software is written by people, rather than robots, and people are affected by the world they live in. 

> Not everyone is American.

That's true, and there are plenty of other awful governments in the world. Unfortunately the Trump administration is in charge of the most powerful democratic country in the world, and capable of affecting the welfare of people all over the globe. Women will die all over the world, because Trump has stripped funding from any international NGO [that provides access to safe abortion](https://www.theguardian.com/world/2017/jan/23/trump-abortion-gag-rule-international-ngo-funding). Parents [separated from their children](https://www.theguardian.com/us-news/2017/jan/29/trump-travel-ban-peoples-stories-from-us-and-around-the-world), for no reason other than racism. The future of the planet, it's air and climate, disregarded - because [science carries no weight with the administration](https://www.theguardian.com/environment/2016/dec/15/trump-cabinet-climate-change-deniers).  I care enough about that to put 3 lines at the end of BFG's output, and I'm happy it's resulted in donations to charities that can make a difference.

> Not everyone cares about politics, or your political agenda.
> It's actually kind of offensive pushing your shit like this in a free tool.

I don't think it's that offensive, but I guess it might offend some people, yes. It's not pushing hatred or stupidity though, so people who aren't interested can probably cope with the inconvenience.

> Anyway, unless or until this political propaganda is removed I won't be using or recommending bfg-repo-cleaner to anyone.

That's fine, you are free to use an alternate tool. Code is a form of expression. You don't have to listen to me speak if you don't want to.
