### ISSUE TITLE
Is there any way to wind back a clean?

### ISSUE THREAD

**Issue by russelljjarvis** [rtyley/bfg-repo-cleaner#262]
Can I convert files like:
setup.py.REMOVED.git-id
back to setup.py etc?

**Comment by javabrett** [comment]
Do you have an unmodified clone of the repo somewhere?

Do you want to revert back to a pre-clean state and clean-again with different options, or do you just want to recover the latest revision of `setup.py`?

**Comment by russelljjarvis** [comment]
Although I have a relatively unmodified clone elsewhere, it was not as up to date as I previously thought.

Yes I want to try to achieve a pre-clean state. I understand that the HEAD or the most recent branch is supposed to be protected, however files ending in the suffix REMOVED.git-id actually appear in the head too.

**Comment by javabrett** [comment]
Step one of the instructions is `$ git clone --mirror git://example.com/some-big-repo.git` ... so either you didn't do this, or have since pushed-back to this repo?

If you haven't run `git gc` yet then chances are your old branch-heads are there in-tact, but it will take a fair bit of doing if you have a lot of branches and/or tags.

**Comment by russelljjarvis** [comment]
I have recovered from the state thanks for the help and the good tool.
